"""
HTML Email Template Generator
Creates beautiful, responsive HTML emails with inline CSS
"""

from datetime import datetime

def generate_html_email(response_text, subject="Auto-Reply", sender_name=None):
    """
    Generate a beautiful HTML email template
    
    Args:
        response_text: The AI-generated response text
        subject: Email subject (optional)
        sender_name: Name of original sender (optional)
        
    Returns:
        str: Complete HTML email with inline CSS
    """
    
    # Split response into paragraphs
    paragraphs = response_text.strip().split('\n\n')
    
    # Generate paragraph HTML
    paragraph_html = ''
    for para in paragraphs:
        if para.strip():
            paragraph_html += f'<p style="margin: 0 0 16px 0; line-height: 1.6; color: #333333;">{para.strip()}</p>\n'
    
    # Current timestamp
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    
    html_template = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{subject}</title>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f5f5f5;">
    <table role="presentation" style="width: 100%; border-collapse: collapse; background-color: #f5f5f5;">
        <tr>
            <td style="padding: 40px 20px;">
                <!-- Main Container -->
                <table role="presentation" style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 12px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); overflow: hidden;">
                    
                    <!-- Header -->
                    <tr>
                        <td style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px 40px; text-align: center;">
                                <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: 600; letter-spacing: -0.5px;">
                                    CortexMail
                                </h1>
                            <p style="margin: 8px 0 0 0; color: #e0e7ff; font-size: 14px;">
                                Cognitive Email Intelligence
                            </p>
                        </td>
                    </tr>
                    
                    <!-- Content Card -->
                    <tr>
                        <td style="padding: 40px;">
                            <!-- Greeting Badge -->
                            <div style="display: inline-block; background-color: #f0f4ff; color: #667eea; padding: 8px 16px; border-radius: 20px; font-size: 13px; font-weight: 500; margin-bottom: 24px;">
                                📧 Automated Response
                            </div>
                            
                            <!-- Message Content -->
                            <div style="margin-top: 20px;">
                                {paragraph_html}
                            </div>
                            
                            <!-- Divider -->
                            <div style="margin: 32px 0; height: 1px; background: linear-gradient(to right, transparent, #e5e7eb, transparent);"></div>
                            
                            <!-- Info Box -->
                            <div style="background-color: #fef3c7; border-left: 4px solid #f59e0b; padding: 16px; border-radius: 6px; margin-top: 24px;">
                                <p style="margin: 0; font-size: 13px; color: #92400e; line-height: 1.5;">
                                    <strong>ℹ️ Note:</strong> This is an automated response generated by AI. A human will review your message and provide a detailed reply if needed.
                                </p>
                            </div>
                        </td>
                    </tr>
                    
                    <!-- Footer -->
                    <tr>
                        <td style="background-color: #f9fafb; padding: 30px 40px; border-top: 1px solid #e5e7eb;">
                            <table role="presentation" style="width: 100%;">
                                <tr>
                                    <td style="text-align: center;">
                                        <p style="margin: 0 0 8px 0; font-size: 13px; color: #6b7280;">
                                            Sent on {timestamp}
                                        </p>
                                        <p style="margin: 0 0 4px 0; font-size: 12px; color: #9ca3af;">
                                            Powered by CortexMail
                                        </p>
                                        <p style="margin: 0; font-size: 10px; color: #9ca3af;">
                                            © 2025 APIWISH ANUTARAVANICHKUL. All rights reserved.
                                        </p>
                                        
                                        <!-- Open Source Attribution -->
                                        <div style="border-top: 1px solid #e5e7eb; margin-top: 20px; padding-top: 12px; text-align: center; color: #6b7280; font-size: 12px;">
                                            This email is based on open source. <a href="https://github.com/apiwishboon-spec/AI-Email-Auto-Reply-System/edit/main/README.md" style="color: #667eea; text-decoration: none;">Improve this open source</a>.
                                        </div>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    
                </table>
                
                <!-- Bottom Spacing -->
                <table role="presentation" style="max-width: 600px; margin: 20px auto 0;">
                    <tr>
                        <td style="text-align: center; padding: 0 20px;">
                            <p style="margin: 0; font-size: 12px; color: #9ca3af; line-height: 1.5;">
                                This email was automatically generated in response to your message.
                            </p>
                        </td>
                    </tr>
                </table>
                
            </td>
        </tr>
    </table>
</body>
</html>
"""
    
    return html_template.strip()


def generate_plain_text(response_text):
    """
    Generate plain text version of email for clients that don't support HTML
    
    Args:
        response_text: The AI-generated response text
        
    Returns:
        str: Plain text email
    """
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    
    plain_text = f"""
CortexMail
Cognitive Email Intelligence

{response_text}

---
Note: This is an automated response generated by AI. A human will review your message and provide a detailed reply if needed.

Sent on {timestamp}
Powered by CortexMail
© 2025 APIWISH ANUTARAVANICHKUL. All rights reserved.
This email is based on open source. Improve this open source: https://github.com/apiwishboon-spec/AI-Email-Auto-Reply-System/edit/main/README.md
"""
    
    return plain_text.strip()
